TYPE=VIEW
query=select `O`.`id` AS `id`,`O`.`name` AS `name`,`O`.`asset_no` AS `asset_no`,`O`.`has_problems` AS `has_problems`,`O`.`comment` AS `comment`,`AV_H`.`uint_value` AS `height`,`AV_S`.`uint_value` AS `sort_order`,`RT`.`thumb_data` AS `thumb_data`,`R`.`id` AS `row_id`,`R`.`name` AS `row_name`,`L`.`id` AS `location_id`,`L`.`name` AS `location_name` from (((((((`racktables`.`Object` `O` left join `racktables`.`AttributeValue` `AV_H` on(`O`.`id` = `AV_H`.`object_id` and `AV_H`.`attr_id` = 27)) left join `racktables`.`AttributeValue` `AV_S` on(`O`.`id` = `AV_S`.`object_id` and `AV_S`.`attr_id` = 29)) left join `racktables`.`RackThumbnail` `RT` on(`O`.`id` = `RT`.`rack_id`)) left join `racktables`.`EntityLink` `RL` on(`O`.`id` = `RL`.`child_entity_id` and `RL`.`parent_entity_type` = \'row\' and `RL`.`child_entity_type` = \'rack\')) join `racktables`.`Object` `R` on(`R`.`id` = `RL`.`parent_entity_id`)) left join `racktables`.`EntityLink` `LL` on(`R`.`id` = `LL`.`child_entity_id` and `LL`.`parent_entity_type` = \'location\' and `LL`.`child_entity_type` = \'row\')) left join `racktables`.`Object` `L` on(`L`.`id` = `LL`.`parent_entity_id`)) where `O`.`objtype_id` = 1560
md5=c17fa9b235ca11af25efe8038679eb27
updatable=0
algorithm=0
definer_user=racktables
definer_host=%
suid=2
with_check_option=0
timestamp=2019-05-11 00:50:33
create-version=2
source=SELECT O.id, O.name AS name, O.asset_no, O.has_problems, O.comment,\n  AV_H.uint_value AS height,\n  AV_S.uint_value AS sort_order,\n  RT.thumb_data,\n  R.id AS row_id,\n  R.name AS row_name,\n  L.id AS location_id,\n  L.name AS location_name\n  FROM `Object` O\n  LEFT JOIN `AttributeValue` AV_H ON O.id = AV_H.object_id AND AV_H.attr_id = 27\n  LEFT JOIN `AttributeValue` AV_S ON O.id = AV_S.object_id AND AV_S.attr_id = 29\n  LEFT JOIN `RackThumbnail` RT ON O.id = RT.rack_id\n  LEFT JOIN `EntityLink` RL ON O.id = RL.child_entity_id  AND RL.parent_entity_type = \'row\' AND RL.child_entity_type = \'rack\'\n  INNER JOIN `Object` R ON R.id = RL.parent_entity_id\n  LEFT JOIN `EntityLink` LL ON R.id = LL.child_entity_id AND LL.parent_entity_type = \'location\' AND LL.child_entity_type = \'row\'\n  LEFT JOIN `Object` L ON L.id = LL.parent_entity_id\n  WHERE O.objtype_id = 1560
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `O`.`id` AS `id`,`O`.`name` AS `name`,`O`.`asset_no` AS `asset_no`,`O`.`has_problems` AS `has_problems`,`O`.`comment` AS `comment`,`AV_H`.`uint_value` AS `height`,`AV_S`.`uint_value` AS `sort_order`,`RT`.`thumb_data` AS `thumb_data`,`R`.`id` AS `row_id`,`R`.`name` AS `row_name`,`L`.`id` AS `location_id`,`L`.`name` AS `location_name` from (((((((`racktables`.`Object` `O` left join `racktables`.`AttributeValue` `AV_H` on(`O`.`id` = `AV_H`.`object_id` and `AV_H`.`attr_id` = 27)) left join `racktables`.`AttributeValue` `AV_S` on(`O`.`id` = `AV_S`.`object_id` and `AV_S`.`attr_id` = 29)) left join `racktables`.`RackThumbnail` `RT` on(`O`.`id` = `RT`.`rack_id`)) left join `racktables`.`EntityLink` `RL` on(`O`.`id` = `RL`.`child_entity_id` and `RL`.`parent_entity_type` = \'row\' and `RL`.`child_entity_type` = \'rack\')) join `racktables`.`Object` `R` on(`R`.`id` = `RL`.`parent_entity_id`)) left join `racktables`.`EntityLink` `LL` on(`R`.`id` = `LL`.`child_entity_id` and `LL`.`parent_entity_type` = \'location\' and `LL`.`child_entity_type` = \'row\')) left join `racktables`.`Object` `L` on(`L`.`id` = `LL`.`parent_entity_id`)) where `O`.`objtype_id` = 1560
mariadb-version=100314
